version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 8000:80
    depends_on:
      - app
    container_name: rest_api_nginx

  app:
    build:
      context: .
      dockerfile: ./_docker/app/Dockerfile
    volumes:
      - ./:/var/www
    container_name: rest_api_app

